{"name": "Ошибка 404 при отправки запроса принятие заказа с невалидным id курьера", "status": "passed", "steps": [{"name": "Принятие заказа", "status": "passed", "start": 1747763955284, "stop": 1747763955434}], "start": 1747763955283, "stop": 1747763955434, "uuid": "afb44954-a1b6-4f7c-b7f1-fc29c791db74", "historyId": "91bdcecb318177ee160d45e11a7816a1", "testCaseId": "91bdcecb318177ee160d45e11a7816a1", "fullName": "tests.test_accept_the_order.TestAcceptTheOrder#test_error_accept_the_order_invalid_id_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptTheOrder"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "9628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}