{"name": "Ошибка 404 при отправки запроса принятие заказа с невалидным id курьера", "status": "passed", "steps": [{"name": "Принятие заказа", "status": "passed", "start": 1747763406624, "stop": 1747763406822}], "start": 1747763406624, "stop": 1747763406822, "uuid": "9205f3ad-893b-4820-9bc5-4d766df72ee4", "historyId": "91bdcecb318177ee160d45e11a7816a1", "testCaseId": "91bdcecb318177ee160d45e11a7816a1", "fullName": "tests.test_accept_the_order.TestAcceptTheOrder#test_error_accept_the_order_invalid_id_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptTheOrder"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "6036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}