{"name": "Ошибка '404' при отправки запроса с несуществующем id на удаление курьера", "status": "passed", "start": 1747765801153, "stop": 1747765801329, "uuid": "4d290e8f-99b0-48b9-a808-b65c1b53a482", "historyId": "86fed0cfe787b4d4fc9e7470d8378f86", "testCaseId": "86fed0cfe787b4d4fc9e7470d8378f86", "fullName": "tests.test_deleted_courier.TestDeletedCourier#test_error_request_without_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_deleted_courier"}, {"name": "subSuite", "value": "TestDeletedCourier"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "8692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_deleted_courier"}]}