{"name": "Ошибка при получении заказа c несуществующим номером", "status": "passed", "steps": [{"name": "Создаём заказ", "status": "passed", "start": 1747765808104, "stop": 1747765808360}, {"name": "Получение заказа", "status": "passed", "start": 1747765808361, "stop": 1747765808531}], "start": 1747765808104, "stop": 1747765808532, "uuid": "0fda451e-27ce-4271-9145-71f28d236372", "historyId": "76b8c0e35c7b63a6b6342197c73d4827", "testCaseId": "76b8c0e35c7b63a6b6342197c73d4827", "fullName": "tests.test_receiving_order_by_track.TestReceivingOrderByTrack#test_error_receiving_order_non_existent_track", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_receiving_order_by_track"}, {"name": "subSuite", "value": "TestReceivingOrderByTrack"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "8692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_receiving_order_by_track"}]}