{"name": "Ошибка '409' при создании двух одинаковых курьеров", "status": "passed", "steps": [{"name": "Создаём двух одинаковых курьеров", "status": "passed", "start": 1747825195475, "stop": 1747825195619}], "start": 1747825195475, "stop": 1747825195620, "uuid": "15f85837-1410-4db5-b0a6-e5eb84e7a11c", "historyId": "acd8d8e8195c89825fb471e3fc9b39be", "testCaseId": "acd8d8e8195c89825fb471e3fc9b39be", "fullName": "tests.test_creating_courier.TestCreatingCourier#test_error_when_creating_two_identical_couriers", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_creating_courier"}, {"name": "subSuite", "value": "TestCreatingCourier"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "7628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_creating_courier"}]}