{"name": "Ошибка 404 при отправки запроса принятие заказа с невалидным id заказа", "status": "passed", "steps": [{"name": "Принятие заказа", "status": "passed", "start": 1747763405106, "stop": 1747763405678}], "start": 1747763405106, "stop": 1747763405678, "uuid": "55b0a058-03a1-49b8-9164-37ec4b81950e", "historyId": "85164a658ac696fd8eefc5407e1a2a9a", "testCaseId": "85164a658ac696fd8eefc5407e1a2a9a", "fullName": "tests.test_accept_the_order.TestAcceptTheOrder#test_error_accept_the_order_invalid_id_order", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptTheOrder"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "6036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}