{"name": "Ошибка 404 при отправки запроса принятие заказа с невалидным id заказа", "status": "passed", "steps": [{"name": "Принятие заказа", "status": "passed", "start": 1747765795564, "stop": 1747765795771}], "start": 1747765795563, "stop": 1747765795772, "uuid": "227acd10-17a6-44b8-a8ef-456d4432819f", "historyId": "85164a658ac696fd8eefc5407e1a2a9a", "testCaseId": "85164a658ac696fd8eefc5407e1a2a9a", "fullName": "tests.test_accept_the_order.TestAcceptTheOrder#test_error_accept_the_order_invalid_id_order", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptTheOrder"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "8692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}