{"name": "Ошибка 404 при отправки запроса принятие заказа с невалидным id курьера", "status": "passed", "steps": [{"name": "Принятие заказа", "status": "passed", "start": 1747825194370, "stop": 1747825194570}], "start": 1747825194370, "stop": 1747825194570, "uuid": "58d1dec4-cba4-4cd5-8c71-5ba5bba94e3e", "historyId": "91bdcecb318177ee160d45e11a7816a1", "testCaseId": "91bdcecb318177ee160d45e11a7816a1", "fullName": "tests.test_accept_the_order.TestAcceptTheOrder#test_error_accept_the_order_invalid_id_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptTheOrder"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "7628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}