{"name": "Ошибка '404' при отправки запроса с несуществующем id на удаление курьера", "status": "passed", "start": 1747825006896, "stop": 1747825007094, "uuid": "a352d18f-044c-4598-9e4e-aced2209c44c", "historyId": "86fed0cfe787b4d4fc9e7470d8378f86", "testCaseId": "86fed0cfe787b4d4fc9e7470d8378f86", "fullName": "tests.test_deleted_courier.TestDeletedCourier#test_error_request_without_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_deleted_courier"}, {"name": "subSuite", "value": "TestDeletedCourier"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "3424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_deleted_courier"}]}