{"name": "Ошибка при получении заказа c несуществующим номером", "status": "passed", "steps": [{"name": "Создаём заказ", "status": "passed", "start": 1747762675550, "stop": 1747762675775}, {"name": "Получение заказа", "status": "passed", "start": 1747762675775, "stop": 1747762675999}], "start": 1747762675549, "stop": 1747762676000, "uuid": "eeaf5c80-acdb-46e5-a858-9a3cf94d0e12", "historyId": "76b8c0e35c7b63a6b6342197c73d4827", "testCaseId": "76b8c0e35c7b63a6b6342197c73d4827", "fullName": "tests.test_receiving_order_by_track.TestReceivingOrderByTrack#test_error_receiving_order_non_existent_track", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_receiving_order_by_track"}, {"name": "subSuite", "value": "TestReceivingOrderByTrack"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "7720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_receiving_order_by_track"}]}