{"name": "Ошибка 404 при отправки запроса принятие заказа с невалидным id курьера", "status": "passed", "steps": [{"name": "Принятие заказа", "status": "passed", "start": 1747765796658, "stop": 1747765796811}], "start": 1747765796657, "stop": 1747765796811, "uuid": "a3648b25-b1f6-4948-b40c-4a505aceb1c1", "historyId": "91bdcecb318177ee160d45e11a7816a1", "testCaseId": "91bdcecb318177ee160d45e11a7816a1", "fullName": "tests.test_accept_the_order.TestAcceptTheOrder#test_error_accept_the_order_invalid_id_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptTheOrder"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "8692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}